//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.03 at 01:03:50 PM CEST 
//


package com.sette.clipping.main.watcher;


import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "count",
    "firstDocumentId",
    "lastDocumentId",
    "lastDocumentDate",
    "firstDocumentDate",
    "articles"
})

@XmlRootElement(name = "ArticleBatch")
public class ArticleBatch {

    @XmlElement(name = "Count")
    protected int count;
    @XmlElement(name = "FirstDocumentId")
    protected int firstDocumentId;
    @XmlElement(name = "LastDocumentId")
    protected int lastDocumentId;
    @XmlElement(name = "LastDocumentDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastDocumentDate;
    @XmlElement(name = "FirstDocumentDate", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar firstDocumentDate;
    @XmlElement(name = "Articles", required = true)
    protected Articles articles;

    /**
     * Gets the value of the count property.
     *
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     *
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the firstDocumentId property.
     *
     */
    public int getFirstDocumentId() {
        return firstDocumentId;
    }

    /**
     * Sets the value of the firstDocumentId property.
     *
     */
    public void setFirstDocumentId(int value) {
        this.firstDocumentId = value;
    }

    /**
     * Gets the value of the lastDocumentId property.
     *
     */
    public int getLastDocumentId() {
        return lastDocumentId;
    }

    /**
     * Sets the value of the lastDocumentId property.
     *
     */
    public void setLastDocumentId(int value) {
        this.lastDocumentId = value;
    }

    /**
     * Gets the value of the lastDocumentDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getLastDocumentDate() {
        return lastDocumentDate;
    }

    /**
     * Sets the value of the lastDocumentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setLastDocumentDate(XMLGregorianCalendar value) {
        this.lastDocumentDate = value;
    }

    /**
     * Gets the value of the firstDocumentDate property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getFirstDocumentDate() {
        return firstDocumentDate;
    }

    /**
     * Sets the value of the firstDocumentDate property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setFirstDocumentDate(XMLGregorianCalendar value) {
        this.firstDocumentDate = value;
    }

    /**
     * Gets the value of the articles property.
     *
     * @return
     *     possible object is
     *     {@link Articles }
     *
     */
    public Articles getArticles() {
        return articles;
    }

    /**
     * Sets the value of the articles property.
     *
     * @param value
     *     allowed object is
     *     {@link Articles }
     *
     */
    public void setArticles(Articles value) {
        this.articles = value;
    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "article"
    })
    public static class Articles {

        @XmlElement(name = "Article", required = true)
        protected List<Article> article;

        /**
         * Gets the value of the article property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the article property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getArticle().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Article }
         *
         *
         */
        public List<Article> getArticle() {
            if (article == null) {
                article = new ArrayList<Article>();
            }
            return this.article;
        }



        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "title",
            "_abstract",
            "url",
            "sourceUrl",
            "relevance",
            "paragraphs",
            "facets",
            "matches",
            "extracts"
        })
        public static class Article {

            @XmlElement(name = "Title", required = true)
            protected String title;
            @XmlElement(name = "Abstract", required = true)
            protected String _abstract;
            @XmlElement(name = "Url", required = true)
            protected String url;
            @XmlElement(name = "SourceUrl", required = true)
            protected String sourceUrl;
            @XmlElement(name = "Relevance")
            protected int relevance;
            @XmlElement(name = "Paragraphs", required = true)
            protected Paragraphs paragraphs;
            @XmlElement(name = "Facets", required = true)
            protected Facets facets;
            @XmlElement(name = "Matches", required = true)
            protected Matches matches;
            @XmlElement(name = "Extracts", required = true)
            protected Extracts extracts;
            @XmlAttribute(name = "Date")
            @XmlSchemaType(name = "dateTime")
            protected Date date;
            @XmlAttribute(name = "DocumentId")
            protected Integer documentId;
            @XmlAttribute(name = "InternalId")
            protected Integer internalId;
            @XmlAttribute(name = "Source")
            protected String source;
            @XmlAttribute(name = "ShortSourceName")
            protected String shortSourceName;
            @XmlAttribute(name = "SourceId")
            protected Integer sourceId;

            /**
             * Gets the value of the title property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the abstract property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAbstract() {
                return _abstract;
            }

            /**
             * Sets the value of the abstract property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAbstract(String value) {
                this._abstract = value;
            }

            /**
             * Gets the value of the url property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the sourceUrl property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSourceUrl() {
                return sourceUrl;
            }

            /**
             * Sets the value of the sourceUrl property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSourceUrl(String value) {
                this.sourceUrl = value;
            }

            /**
             * Gets the value of the relevance property.
             *
             */
            public int getRelevance() {
                return relevance;
            }

            /**
             * Sets the value of the relevance property.
             *
             */
            public void setRelevance(int value) {
                this.relevance = value;
            }

            /**
             * Gets the value of the paragraphs property.
             *
             * @return
             *     possible object is
             *     {@link Paragraphs }
             *
             */
            public Paragraphs getParagraphs() {
                return paragraphs;
            }

            /**
             * Sets the value of the paragraphs property.
             *
             * @param value
             *     allowed object is
             *     {@link Paragraphs }
             *
             */
            public void setParagraphs(Paragraphs value) {
                this.paragraphs = value;
            }

            /**
             * Gets the value of the facets property.
             *
             * @return
             *     possible object is
             *     {@link Facets }
             *
             */
            public Facets getFacets() {
                return facets;
            }

            /**
             * Sets the value of the facets property.
             *
             * @param value
             *     allowed object is
             *     {@link Facets }
             *
             */
            public void setFacets(Facets value) {
                this.facets = value;
            }

            /**
             * Gets the value of the matches property.
             *
             * @return
             *     possible object is
             *     {@link Matches }
             *
             */
            public Matches getMatches() {
                return matches;
            }

            /**
             * Sets the value of the matches property.
             *
             * @param value
             *     allowed object is
             *     {@link Matches }
             *
             */
            public void setMatches(Matches value) {
                this.matches = value;
            }

            /**
             * Gets the value of the extracts property.
             *
             * @return
             *     possible object is
             *     {@link Extracts }
             *
             */
            public Extracts getExtracts() {
                return extracts;
            }

            /**
             * Sets the value of the extracts property.
             *
             * @param value
             *     allowed object is
             *     {@link Extracts }
             *
             */
            public void setExtracts(Extracts value) {
                this.extracts = value;
            }

            /**
             * Gets the value of the date property.
             *
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public Date getDate() {
                return date;
            }

            /**
             * Sets the value of the date property.
             *
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *
             */
            public void setDate(Date value) {
                this.date = value;
            }

            /**
             * Gets the value of the documentId property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getDocumentId() {
                return documentId;
            }

            /**
             * Sets the value of the documentId property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setDocumentId(Integer value) {
                this.documentId = value;
            }

            /**
             * Gets the value of the internalId property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getInternalId() {
                return internalId;
            }

            /**
             * Sets the value of the internalId property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setInternalId(Integer value) {
                this.internalId = value;
            }

            /**
             * Gets the value of the source property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getSource() {
                return source;
            }

            /**
             * Sets the value of the source property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setSource(String value) {
                this.source = value;
            }

            /**
             * Gets the value of the shortSourceName property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getShortSourceName() {
                return shortSourceName;
            }

            /**
             * Sets the value of the shortSourceName property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setShortSourceName(String value) {
                this.shortSourceName = value;
            }

            /**
             * Gets the value of the sourceId property.
             *
             * @return
             *     possible object is
             *     {@link Integer }
             *
             */
            public Integer getSourceId() {
                return sourceId;
            }

            /**
             * Sets the value of the sourceId property.
             *
             * @param value
             *     allowed object is
             *     {@link Integer }
             *
             */
            public void setSourceId(Integer value) {
                this.sourceId = value;
            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "string"
            })
            public static class Extracts {

                @XmlElement(required = true)
                protected String string;

                /**
                 * Gets the value of the string property.
                 *
                 * @return
                 *     possible object is
                 *     {@link String }
                 *
                 */
                public String getString() {
                    return string;
                }

                /**
                 * Sets the value of the string property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *
                 */
                public void setString(String value) {
                    this.string = value;
                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "facet"
            })
            public static class Facets {

                @XmlElement(name = "Facet", required = true)
                protected List<Facet> facet;

                /**
                 * Gets the value of the facet property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the facet property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getFacet().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Facet }
                 *
                 *
                 */
                public List<Facet> getFacet() {
                    if (facet == null) {
                        facet = new ArrayList<Facet>();
                    }
                    return this.facet;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 *
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 *
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Items">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="Item">
                 *                     &lt;complexType>
                 *                       &lt;complexContent>
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                           &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                           &lt;attribute name="ParentId" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *                           &lt;attribute name="Name" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *                         &lt;/restriction>
                 *                       &lt;/complexContent>
                 *                     &lt;/complexType>
                 *                   &lt;/element>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}int" />
                 *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 *
                 *
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "items"
                })
                public static class Facet {

                    @XmlElement(name = "Items", required = true)
                    protected Items items;
                    @XmlAttribute(name = "Id")
                    protected Integer id;
                    @XmlAttribute(name = "Type")
                    protected String type;

                    /**
                     * Gets the value of the items property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Items }
                     *
                     */
                    public Items getItems() {
                        return items;
                    }

                    /**
                     * Sets the value of the items property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Items }
                     *
                     */
                    public void setItems(Items value) {
                        this.items = value;
                    }

                    /**
                     * Gets the value of the id property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *
                     */
                    public Integer getId() {
                        return id;
                    }

                    /**
                     * Sets the value of the id property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *
                     */
                    public void setId(Integer value) {
                        this.id = value;
                    }

                    /**
                     * Gets the value of the type property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setType(String value) {
                        this.type = value;
                    }



                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "item"
                    })
                    public static class Items {

                        @XmlElement(name = "Item", required = true)
                        protected Item item;

                        /**
                         * Gets the value of the item property.
                         *
                         * @return
                         *     possible object is
                         *     {@link Item }
                         *
                         */
                        public Item getItem() {
                            return item;
                        }

                        /**
                         * Sets the value of the item property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link Item }
                         *
                         */
                        public void setItem(Item value) {
                            this.item = value;
                        }



                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "")
                        public static class Item {

                            @XmlAttribute(name = "Id")
                            protected Integer id;
                            @XmlAttribute(name = "ParentId")
                            protected Integer parentId;
                            @XmlAttribute(name = "Name")
                            protected String name;

                            /**
                             * Gets the value of the id property.
                             *
                             * @return
                             *     possible object is
                             *     {@link Integer }
                             *
                             */
                            public Integer getId() {
                                return id;
                            }

                            /**
                             * Sets the value of the id property.
                             *
                             * @param value
                             *     allowed object is
                             *     {@link Integer }
                             *
                             */
                            public void setId(Integer value) {
                                this.id = value;
                            }

                            /**
                             * Gets the value of the parentId property.
                             *
                             * @return
                             *     possible object is
                             *     {@link Integer }
                             *
                             */
                            public Integer getParentId() {
                                return parentId;
                            }

                            /**
                             * Sets the value of the parentId property.
                             *
                             * @param value
                             *     allowed object is
                             *     {@link Integer }
                             *
                             */
                            public void setParentId(Integer value) {
                                this.parentId = value;
                            }

                            /**
                             * Gets the value of the name property.
                             *
                             * @return
                             *     possible object is
                             *     {@link String }
                             *
                             */
                            public String getName() {
                                return name;
                            }

                            /**
                             * Sets the value of the name property.
                             *
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *
                             */
                            public void setName(String value) {
                                this.name = value;
                            }

                        }

                    }

                }

            }



            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "match"
            })
            public static class Matches {

                @XmlElement(name = "Match", required = true)
                protected Match match;

                /**
                 * Gets the value of the match property.
                 *
                 * @return
                 *     possible object is
                 *     {@link Match }
                 *
                 */
                public Match getMatch() {
                    return match;
                }

                /**
                 * Sets the value of the match property.
                 *
                 * @param value
                 *     allowed object is
                 *     {@link Match }
                 *
                 */
                public void setMatch(Match value) {
                    this.match = value;
                }



                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "words"
                })
                public static class Match {

                    @XmlElement(name = "Words", required = true)
                    protected Words words;
                    @XmlAttribute(name = "Type")
                    protected String type;
                    @XmlAttribute(name = "Text")
                    protected String text;
                    @XmlAttribute(name = "Count")
                    protected Integer count;

                    /**
                     * Gets the value of the words property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Words }
                     *
                     */
                    public Words getWords() {
                        return words;
                    }

                    /**
                     * Sets the value of the words property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Words }
                     *
                     */
                    public void setWords(Words value) {
                        this.words = value;
                    }

                    /**
                     * Gets the value of the type property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                    /**
                     * Gets the value of the text property.
                     *
                     * @return
                     *     possible object is
                     *     {@link String }
                     *
                     */
                    public String getText() {
                        return text;
                    }

                    /**
                     * Sets the value of the text property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *
                     */
                    public void setText(String value) {
                        this.text = value;
                    }

                    /**
                     * Gets the value of the count property.
                     *
                     * @return
                     *     possible object is
                     *     {@link Integer }
                     *
                     */
                    public Integer getCount() {
                        return count;
                    }

                    /**
                     * Sets the value of the count property.
                     *
                     * @param value
                     *     allowed object is
                     *     {@link Integer }
                     *
                     */
                    public void setCount(Integer value) {
                        this.count = value;
                    }



                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "word"
                    })
                    public static class Words {

                        @XmlElement(name = "Word", required = true)
                        protected List<Word> word;

                        /**
                         * Gets the value of the word property.
                         *
                         * @return
                         *     possible object is
                         *     {@link Word }
                         *
                         */
                        public List<Word> getWord() {
                        	if (word == null) {
                                word = new ArrayList<Word>();
                            }
                            return this.word;
                        }

                        /**
                         * Sets the value of the word property.
                         *
                         * @param value
                         *     allowed object is
                         *     {@link Word }
                         *
                         */
                        public void setWord(List<Word> value) {
                            this.word = value;
                        }



                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "")
                        public static class Word {

                            @XmlAttribute(name = "Text")
                            protected String text;
                            @XmlAttribute(name = "Count")
                            protected Integer count;

                            /**
                             * Gets the value of the text property.
                             *
                             * @return
                             *     possible object is
                             *     {@link String }
                             *
                             */
                            public String getText() {
                                return text;
                            }

                            /**
                             * Sets the value of the text property.
                             *
                             * @param value
                             *     allowed object is
                             *     {@link String }
                             *
                             */
                            public void setText(String value) {
                                this.text = value;
                            }

                            /**
                             * Gets the value of the count property.
                             *
                             * @return
                             *     possible object is
                             *     {@link Integer }
                             *
                             */
                            public Integer getCount() {
                                return count;
                            }

                            /**
                             * Sets the value of the count property.
                             *
                             * @param value
                             *     allowed object is
                             *     {@link Integer }
                             *
                             */
                            public void setCount(Integer value) {
                                this.count = value;
                            }

                        }

                    }

                }

            }


            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "paragraph"
            })
            public static class Paragraphs {

                @XmlElement(name = "Paragraph", required = true)
                protected List<Paragraph> paragraph;

                /**
                 * Gets the value of the paragraph property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the paragraph property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getParagraph().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Paragraph }
                 *
                 *
                 */
                public List<Paragraph> getParagraph() {
                    if (paragraph == null) {
                        paragraph = new ArrayList<Paragraph>();
                    }
                    return this.paragraph;
                }


               
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "text"
                })
                public static class Paragraph {

                    @XmlElement(name = "Text", required = true)
                    protected String text;
                    @XmlAttribute(name = "Type")
                    protected String type;

                    /**
                     * Gets the value of the text property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getText() {
                        return text;
                    }

                    /**
                     * Sets the value of the text property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setText(String value) {
                        this.text = value;
                    }

                    /**
                     * Gets the value of the type property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getType() {
                        return type;
                    }

                    /**
                     * Sets the value of the type property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setType(String value) {
                        this.type = value;
                    }

                }

            }

        }

    }

}
